version: 2
jobs:
  compile:
    docker:
      - image: fadlyas/kernel_dockerfile:latest
    steps:
      - checkout
      - run: git clone --quiet -j32 --depth=1 https://github.com/fadlyas07/scripts noob
      - run: bash noob/rolex.sh
  compiletoo:
    docker:
      - image: fadlyas/kernel_dockerfile:latest
    steps:
      - checkout
      - run: git clone --quiet -j32 --depth=1 https://github.com/fadlyas07/scripts noob
      - run: bash noob/riva.sh
workflows:
  version: 2
  cooking:
    jobs:
      - compile
      - compiletoo
