version: 2.1
jobs:
  compile:
    docker:
      - image: mhmmdfas/mydockerimage:latest
    steps:
      - run: git clone -j32 https://github.com/fadlyas07/android-kernel-xiaomi-msm8917-common -b google-common --depth=1 .
      - run: wget https://raw.githubusercontent.com/fadlyas07/scripts/master/pure/rolex
      - run: chmod +x rolex
      - run: bash rolex
  compiletoo:
    docker:
      - image: mhmmdfas/mydockerimage:latest
    steps:
      - run: git clone -j32 https://github.com/fadlyas07/android-kernel-xiaomi-msm8917-common -b google-common --depth=1 .
      - run: wget https://raw.githubusercontent.com/fadlyas07/scripts/master/pure/riva
      - run: chmod +x riva
      - run: bash riva
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
      - compiletoo
